[package]
name = "themelio-bxms"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
smol= "1.2.5"
anyhow= "1.0.43"
themelio-stf= "0.5.3"
tmelcrypt= "0.1.0"
themelio-nodeprot= "0.4.1"
structopt= "0.3.22"
once_cell= "1.8.0"
hex= "0.4.3"

tracing-subscriber = "0.2.20"

log= "0.4.14"
tracing= "0.1.26"

askama= "0.10.5"

serde={ version = "1.0.127", features = ["derive"] }
num-traits= "0.2.14"

futures-util= "0.3.16"
chrono={ version = "0.4.19", features = ["serde"] }
serde_json= "1.0.66"
