[package]
name = "melscan-backend"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>", "sshmendez <shane@themelio.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
# this patches the themelio-nodeprot that themelio-bootstrap depends on too
# themelio-nodeprot={path="../../themelio-nodeprot"} 

[dependencies]
# tide = "0.16.0"
smol= "1.2.5"
anyhow= "1.0.58"
themelio-stf= "0.11.2"
tmelcrypt= "0.2.4"
themelio-nodeprot= "0.11.5"
#themelio-nodeprot= {path="../../themelio-nodeprot"}
melblkidx="0.5"
structopt= "0.3.26"
once_cell= "1.13.0"
hex= "0.4.3"
thread_local="1.1"
warp = "0.3.2"
rweb = "0.15.0"
tokio = "1.19.2"

tracing-subscriber = {version="0.3.14", features=["env-filter"]}

log= "0.4.17"
tracing= "0.1.35"

# askama= { version = "0.11.1", features = ["serde-json"] }

serde={ version = "1.0.139", features = ["derive"] }
num-traits= "0.2.15"
 
futures-util= "0.3.21"
chrono={ version = "0.4.19", features = ["serde"] }
serde_json= "1.0.82"
themelio-bootstrap= "0.6.0"

lazy_static = "1.4.0"
# cached = "0.25.1"
async-trait = "0.1.56"
dashmap = "5.3.4"
themelio-structs = "0.2.6"
smolscale = "0.3.29"
parking_lot = "0.12.1"
stdcode = "0.1.7"
defmac = "0.2.1"
env_logger = "0.9.0"
itertools = "0.10.3"
serde_with = "1.14.0"
moka = "0.9.2"
tap = "1.0.1"


[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled"]

